In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [3]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
x.sum(axis=0)

array([12, 15, 18])

In [5]:
x.argmax(axis=0)

array([2, 2, 2])